var works = [
  {title: "Glam by Adelina",
  	pic: "img/portfolio/glam/GlamCombo.png",
  	url: "http://www.glambyadelina.com/"},
  {title:"A Squared Accessories",
    pic: "img/portfolio/a2/A2Combo.png",
    url: "https://eidelbikes.herokuapp.com/"},
  {title: "Eidelhaus",
  	pic: "img/portfolio/eidelhaus/EidelhausCombo.png",
  	url: "http://www.eidelhaus.com"},
  {title:"Eideldev",
    pic: "img/portfolio/eideldev/EideldevCombo.png",
    url: "i-dont-usually-link-to-a-404-but-when-i-do-it-features-boba-fett"},
  {title: "Gameplan Jobs",
    pic: "img/portfolio/gpj/GameplanCombo.png",
    url: "http://www.gameplanjobs.com/"},
  {title:"[PROTOTYPE] Grad Jobs",
    pic: "img/portfolio/gradjobs/GradJobsCombo.png",
    url: "http://gene.bitballoon.com/"}
]
